### ISSUE TITLE
Jinja template maken van een html template

### ISSUE THREAD

**Issue by nicolaydammer** [nicolaydammer/webtechnologie#1]
Je moet uitzoeken hoe je met jinja templates kunt maken van de header (navigatie balk) en footer. Hiervoor moet je eerst een html template hebben (https://startbootstrap.com/themes) zet dit in een branch. met deze issue

**Comment by SjoerdFroma** [comment]
https://startbootstrap.com/previews/blog-home  een van deze twee deze template.
